<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>RSLauncher.Auth</AssemblyName>
    <RootNamespace>RSLauncher.Auth</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CmlLib.Core.Auth.Microsoft" Version="3.3.1" />
  </ItemGroup>
</Project>
